- _profiles/ben-peachey.md
Awarding thumb badge for all the work done on the achievement site
> Adding thumb badge for Ben

- _profiles/gert-jan-scholten.md
For his diligent and dedicated work in regards to the scrum master role.
@eaulav / @arjank Can one of you guys back this?
> Rewards thumb up to Gert-Jan

- _profiles/olav-rings.md
- For working hard to cleanup and refactor legacy code
- For coming up with various improvements
> Rewards thumb up and lagacy-project to Olav

- _profiles/frank-kuiper.md
For making an obvious mistake.
> Awards the "sack of hay" badge to Frank

- _profiles/lotte-veldhof.md
For convincing a product owner of the value of "her" ticket.
Well done!
> Awards a thumbup to Lotte

- _profiles/ben-peachey.md
For keeping a big-ass-todo-list (as awarded by Wouter and backed by Gert-Jan).
> Awards pencil to Ben

- _profiles/arjan-kleene.md
For adding outstanding ideas to our discussion about "naming things" and for his SQL work.
> Awards a thumbup to Arjan

- _profiles/daniel-ravenshorst.md
I gave Daniel a thumbs up, not sure for what anymore but he deserved it!
> Thumbs up Daniel unknown reasons

- _profiles/arjan-kleene.md
- _profiles/ben-peachey.md
- _profiles/daniel-ravenshorst.md
- _profiles/frank-kuiper.md
- _profiles/gert-jan-scholten.md
- _profiles/lotte-veldhof.md
- _profiles/olav-rings.md
reset the scores so the new sprint can start where everyone has zero badges
> resetting scores for the new sprint

- _profiles/gert-jan-scholten.md
Because he prevented a disturbance
> beer for Gert-Jan

- _profiles/chris-broeren.md
Chris fixxed the coffee-machine, we have good coffee again!
> Fixxed the coffee-machine

- _data/members.json
- _profiles/linsey-van-der-veen.md
> Badge for Linsey

- _profiles/daniel-ravenshorst.md
because he broke my plantpot :sadface:
> adds easter egg for daniel

- _layouts/profile.html
> bugfix to only show svg badges on profile

- _includes/list-all-badges.lqd
- _layouts/profile.html
> Bugfix to only show SVG badges.

- _profiles/daniel-ravenshorst.md
> Daniel working with legacy

- _profiles/wouter-oosterveld.md
Because he didn't answer our skype call (daily stand-up)
> Easter egg for Wouter Oosterveld

- _data/members.json
Vincent stevens deserved a badge, but we need to add him first.
> Added vincent stevens to members

- _profiles/vincent-stevens.md
> Created a Brnach

- .lgtm
> Adds "ship" emoji to LGTM config.

- _profiles/ferry-joosten.md
For missing my talk during the stand-up because he was to late and than asking afterwards if I could do it again just for afterwards
> Sackofhay for Ferry

- _profiles/linsey-van-der-veen.md
For making clear specification/tickets.
> Awards the party hat to Linsey

- _profiles/daniel-ravenshorst.md
For not building that thing generic, causing refactor work.
> Awards the paasei award to Daniel

- _profiles/gert-jan-scholten.md
For "something" during the estimates.
> Awards a zak-hooi to Gert-Jan

- _profiles/olav-rings.md
> Not sure if trolling or serious

- _profiles/olav-rings.md
For improving and refactoring dat legacy code.
> Awards the progress badge to Olav

- _profiles/ben-peachey.md
> Thumb for Ben for helping with refactor

- _profiles/arthur-prinsen.md
- For failing to notify the PO this campagne was cancelled.
> Arthur Sack of Hay

- README.md
> added ship emoji to lgtm approve messages

- _profiles/qi-lin.md
There was a lack of knowledge with the 2 stakeholders.
> Qi Deflected a fast lane

- _profiles/chris-broeren.md
For getting us some super stickies
> Awards a thumbup to Chris

- _profiles/vincent-stevens.md
For being mentioned in the sprint review.
> Awards happy and sad faces to Vincent

- _profiles/vincent-stevens.md
> Awards a "level up" to Vincent

- _profiles/ben-peachey.md
Failed to communicate that the hours of Olaf are not in the sprint so Olaf can goof around.
> You Particked!

- _profiles/gert-jan-scholten.md
Because he changed a query without changing the return array
> Easter egg for Gert-jan

- _profiles/olav-rings.md
For further cleaning up of the assets repo.
> Awards a progress to Olav

- _profiles/gert-jan-scholten.md
> Awards progress to Gert-Jan

- _profiles/meike-maasmann.md
@pimkaptein You might want to approve this a.s.a.p.
> Fixing wrong badge assigned by Mr. PaasEi.

- _profiles/pim-kaptein.md
> Awards easter-egg to Pim

- _profiles/olav-rings.md
For be braving enough to say "I don't know this".
> Awards comment to Olav

- _profiles/franck-nijhof.md
> Thumbs up for Franck

- _data/members.json
- _profiles/knut-jaegersberg.md
So we can give him some nice badges!
> Adds Knut to members file.

- _profiles/pim-kaptein.md
Nominate pim for adding new members (Narek and Meike) to the achievement gamification
> Narek:Thumbsup for Pim

- _profiles/vincent-stevens.md
> Awards progress badge to Vincent

- _profiles/gert-jan-scholten.md
- For being a very good co-worker and driving me to and from work every day for a week
- For assisting me in the code, keeping me sharp and being a co-pilot/pair programmer
- For looking after me when I was struggling to keep my daily structure.
> Awards 3 badges to Gert-Jan

- _profiles/arjan-kleene.md
For not telling her in time that he wasn't there.
> Linsey awards the sack of hay to Arjan

- _profiles/pim-kaptein.md
Since I'm on a holiday, Pim tried to create an new JIRA project for DataScience. Although I appreciate the effort, he did not follow the newly created JIRA workflows and schemes for DealerDirect.
This causes JIRA to generate all kinds of stuff, we were trying to get rid of....
Next time Pim, please copy one of the newly created projects on project creation.
> Putting up Pim for an easter egg!

- _profiles/daniel-ravenshorst.md
For writing a very good comment, clear and obvious! Very well done [DEV-105](https://dealerdirect.atlassian.net/browse/DEV-105?focusedCommentId=23590&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-23590)
> Add Thumbs-up for Daniel

- _profiles/olav-rings.md
Ferry wants to award Olav a badge. He is happy with the idea Olav has put in Jira!!!
> Award a badge for Olav (idea)

- _profiles/mitchell-busschers.md
For updating wiki pages and diving straight into docs, diagrams and other difficulty.
> Awards a thumbup to Mitchell

- _profiles/franck-nijhof.md
> Easter egg for Franck

- _profiles/arjan-kleene.md
Arjan should get a huge THUMBS-UP for fixen the fastlane Soap api call fails
> Thumbs-up for Arjan (Ferry requested)

- _profiles/mitchell-busschers.md
For learning all them new technologies.
> Awards progress to Mitchell

- _profiles/arjan-kleene.md
- _profiles/gert-jan-scholten.md
For collaborating like a real team!
> Arjan and Gert-Jan teamwork

- _profiles/mitchell-busschers.md
A Patrick for switching Knut with Ben and vice-versa.
> Give Mitchell a Patrick

- _profiles/mitchell-busschers.md
1) for tagging his own repo with the sprint name instead of the achievement one
2) For telling me i should be glad to not have kids, 1 second after i tell him my kid does stuff...
> Award Mitchell a Patrick

- _profiles/pim-kaptein.md
> beer for pim

- _profiles/frank-kuiper.md
For being mentioned in a retrospective in a positive way. @DealerDirect/admins please approve. :D
> Give Frank a badge

- _profiles/vincent-stevens.md
For being mentioned in a retrospective in a positive way. @DealerDirect/admins please approve. :D
> Give Vincent a badge

- _profiles/edward-de-wit.md
For getting everybody headphones.
> Awards a thumbup to Edward

- _profiles/ben-peachey.md
He committed a fix directly to master.
> Sack of Hay for B.peachey

- _profiles/gert-jan-scholten.md
For work on the Thuiswinkelwaarborg and other related issues.
> Awards security to Gert-Jan

- _profiles/vincent-stevens.md
Thumbs up for Vincent for diving into NewRelic. He is the first one to actually improve / fix stuff indicated by NR.
> Thumbs up for Vincent

- _profiles/knut-jaegersberg.md
For making a presentation on point.
> Awards dart to Knut

- _profiles/frank-kuiper.md
For working with Github:
- Creating a commit
- Creating a pull-request
- Merging a pull request
- Deleting a branch
> Awards magic to Frank

- _profiles/wouter-oosterveld.md
Award the Patrick for not thinking when creating a PR and within the same minute (or almost the same) declining it.
> Award a Patrick to Wouter

- _profiles/arjan-kleene.md
Ferry wants to award Arjan a medal for his understanding and a thumbs up for his patience with the PO
> Award Arjan a Medal and Thumbs up!

- _profiles/pim-kaptein.md
For getting me coffee several times while I was moving on crutches.
> Awarded coffee badge to Pim

- _profiles/franck-nijhof.md
An important bug was discovered and fixed
> Award Franck a progress badge for using New Relic

- _profiles/olav-rings.md
An important bug was discovered and fixed
> Award Olav a progress badge for using New Relic

- _profiles/mitchell-busschers.md
A coffee badge for getting me coffee at least once while I was moving around on crutches, and a Patrick because he keeps asking for a badge.
> Badges for Mitchell

- _profiles/ferry-joosten.md
> Awards pie to Ferry

- _profiles/gert-jan-scholten.md
> Awards legacy to Gert-Jan

- _profiles/ben-peachey.md
> Had wrong commit, Ben forced me to fix.

- css/modules/achievements.css
> Fixes grayed out bug in achievements.css by changing filter order.

- _data/members.json
- _profiles/empty.md
- _profiles/robert-page.md
- Adds "pie" to empty.md so that all user will have that badge in their profiles the next time the profiles are updated with the sprint reset
- Sorts users in `members.json` alphabetically
- Adds profile and data entry for Robert Page
Closes #175
> Adds Robert Page (and minor cleanup)

- _profiles/gert-jan-scholten.md
For his comments in "the" peer review.
> Awards pedantic badge to Gert-Jan

- _profiles/pim-kaptein.md
Pim solved a blocking ticket, now we can continue this tickets.
> Progress for Pim,

- _profiles/lotte-veldhof.md
For winning "Who did the dishes".
> Awards crown to Lotte

- _profiles/ben-peachey.md
> Easteregg for Ben

- _profiles/gert-jan-scholten.md
Immediately commenting, not reading first, asking a question he could have answered himself if he looked further then his nose long is.
> A Patrick for GJ for not reading and assuming

- _profiles/olav-rings.md
Olav made the smart call to offer Pim a cookie, so he wouldn't get eaten by Pim (many hungry!!!!)
> For offering a cookie to Pim

- _profiles/ferry-joosten.md
For selflessly helping out doing the dishes by hand when the dishwasher croaked.
> Awards Teamwork badge

- _profiles/gert-jan-scholten.md
For comitting a file that he shouldn't have.
> Awards patrick to Gert-Jan

- _profiles/frank-kuiper.md
For making the awesome burn-down race track!
> Awards crown to Frank

- _profiles/daniel-ravenshorst.md
- _profiles/gert-jan-scholten.md
- _profiles/wouter-oosterveld.md
For the collaborative hotfix effort.
> Awards teamwork to Wouter/Daniel/Gert-Jan

- _profiles/mitchell-busschers.md
For creating dealerdirect bingo
> thumb for mitchell-busschers.md

- _profiles/daniel-ravenshorst.md
For finding a structural glitch early in the process
> For finding a critical glitch in the url scheme

- _profiles/pim-kaptein.md
For finding and returning Geertje's earring.
> Awards smiley to Pim (ask requested by Geertje)

- _profiles/bram-mittendorff.md
> For diving straight into our codebase

- _profiles/wouter-oosterveld.md
For resolving 7 of the 8 issue needed for my local vagrant box to work.
> Awards magic to Wouter

- _profiles/ben-peachey.md
Teamplayer: For putting in extra work and helping out getting the TDD Workshop running and going.
Education: For helping further the knowledge and capabilities of the team concerning test driven development.
> Awards teamplayer and education badge to ben

- _profiles/mart-jan-bakker.md
For setting up the perfect if statement that returns 3 times the same values:
```
@if ($camper == true)
{{ Form::textarea('comment', null, [ 'class' => 'form-control', 'rows' => '3']) }}
@elseif ($caravan == true)
{{ Form::textarea('comment', null, [ 'class' => 'form-control', 'rows' => '3']) }}
@else
{{ Form::textarea('comment', null, [ 'class' => 'form-control', 'rows' => '3']) }}
@endif
```
> Easter egg for Mart-jan

- _profiles/franck-nijhof.md
- CI
- Easier time logging in Jira
- Tasks can now block PR's in ButtBucket
- More stuff
> For all the shit Franck has done in this sprint

- _profiles/mitchell-busschers.md
for putting a leaking beer on my desk instead of his own
> sack of hay for mitchell

- _profiles/mitchell-busschers.md
For enforcing CI testing in his project
> Awarding progress to Mitchel

- _profiles/olav-rings.md
> For making a very good joke

- _profiles/mitchell-busschers.md
For writing with a permanent marker on a whiteboard.
> Easter egg for Mitchell

- _profiles/mitchell-busschers.md
Giving him a thumbs-up for the nice demo to Marketing.
> Thumbs-up for mitchell

- _profiles/franck-nijhof.md
> Give Franck a badge for his pipeline education

- _profiles/gert-jan-scholten.md
For switching numbers in the ticket and opening Arjans ticket
> Sack of hay for GJ

- _profiles/christian-ropertz.md
For winning the "Who did the dishes" challenge.
> Award crown to Christian

- _profiles/ben-peachey.md
For bringing up the idea to put my project up on the team dashboard.
> Awards Idea to Ben

- _profiles/gert-jan-scholten.md
For willing to host my project to allow me to show it to people online.
> Awards Teamplayer to Gert-Jan

- _profiles/bram-mittendorff.md
For commenting in a conversation between me and Linsey telling Linsey to stick to the scrum process.
> Comment badge for Bram

- _profiles/wouter-oosterveld.md
For suggesting to remove all that shiz instead of trying to patch it.
> Awards bullseye to wouter

- _profiles/olav-rings.md
> For bringing "Pepernoten" to the office

- _profiles/mitchell-busschers.md
For bringing pepernuts
https://www.youtube.com/watch?v=R2vBZuLI3oI
> Pie for Mitchell

- _profiles/bram-mittendorff.md
For arranging coffee for everyone!
> Awards coffee badge to Bram

- _profiles/ben-peachey.md
- _profiles/bram-mittendorff.md
- _profiles/christian-ropertz.md
- _profiles/franck-nijhof.md
- _profiles/gert-jan-scholten.md
- _profiles/mitchell-busschers.md
- _profiles/olav-rings.md
- _profiles/pim-kaptein.md
- _profiles/wouter-oosterveld.md
> reset sprint

- _profiles/vincent-stevens.md
You stayed around during the PHP upgrade which is a good thing!
> For being mentioned positively in the Sprint Retro

- _profiles/olav-rings.md
> Olav broke the site, Multiple times.

- _profiles/ferry-joosten.md
For standing up for himself. (As requested by Maaike).
> Awards thumb-up to Ferry

- _profiles/chris-broeren.md
> He refilled the almighty coffee beans

- _profiles/mitchell-busschers.md
For forgetting to pass on the happy birthday card for Arjan.
> Easteregg for Mitchell

- _profiles/bram-mittendorff.md
- _profiles/pim-kaptein.md
> Awards Beer to Bram and Pim

- _profiles/lotte-veldhof.md
For arranging birthday decorations for Arjan even tho she had a day off and fixing the birthday card that Mitchell forgot to pass on.
> Party badge for Lotte

- _profiles/olav-rings.md
For extracting code and putting in a file without importing the new file.
> Awards Olav a Patrick

- _profiles/franck-nijhof.md
for cleaning up the cronjob repo
> Sledgehammer for Franck

- _profiles/chris-broeren.md
For communicating important stuff via email.
> Maillove badge for Chris

- _profiles/dieter-struik.md
For asking questions and getting help.
> Awards Thumb badge to Dieter

- _profiles/daniel-ravenshorst.md
Not sure if he said `Works on my machine` or not.
> Not sure if he said

- _profiles/robert-page.md
For documenting whio is green/blue on the whiteboard
> Upvote Robert

- _profiles/franck-nijhof.md
for awesome teamwork on the certificate signing module
> Teamwork for Franck

- _profiles/daniel-ravenshorst.md
For insulting an enitre nation.
> Awards easter egg to Daniel

- _profiles/ben-peachey.md
For just typing in code without checking it.
> Awards Easter egg to Ben

- _layouts/profile.html
makes the badge name show on hover
> Add badge name in img.title

- _profiles/franck-nijhof.md
A thumbs up has been deserved for getting us all down to earth again, and shine a light on what really needs to happen
> For giving a presentation

- _profiles/maaike-ronhaar.md
For commenting on the wrong ticket that has nothing to do with each other.
> easter-egg for Maaike

- css/modules/achievements.css
Resolves issue raised in PR #290
> CHANGE: Changes hover style so "title" works.

- _profiles/bram-mittendorff.md
- _profiles/chris-broeren.md
- _profiles/daniel-ravenshorst.md
- _profiles/ferry-joosten.md
- _profiles/franck-nijhof.md
- _profiles/maaike-ronhaar.md
- _profiles/olav-rings.md
For their effort and deliverable. Good Job!
> 👑 Awards crown to the Februari Hackathon Team 👍

- _profiles/daniel-ravenshorst.md
For not reading the ticket properly and starting work in the wrong repo.
> ⭐🐟 Awards Patrick to Daniel

- _profiles/pim-kaptein.md
Merged a change, and did not tag it at all. happens by coincidence again
> Merging and not tagging

- _profiles/olav-rings.md
For making an effort to improve the quality of tickets.
> Awards magic to Olav - As requested by Maaike

- _profiles/frank-kuiper.md
For fucking up the logo in french
> Award frank a easteregg

- css/base-theme.css
> CHANGE: Replaces blue color scheme with new corporate identity green color scheme.

- _profiles/gert-jan-scholten.md
As requested by Maaike: For communicating like a pro.
> Awards thumb-up to Gert-Jen
